### PR TITLE
fix webview not responsive on IOS

### PR DESCRIPTION
**Pull request by HyperSimon**
```html
<meta name="viewport" content="width=device-width, initial-scale=1" />
```

I just add this line only. The rest of the change is that I formatted your code, If you do not agree with the new code format, then add the above line into the source code will be fun

| before | after | 
| ------| ------ | 
| simulator screen shot 2017 5 6 5 21 08 | simulator screen shot 2017 5 6 5 20 46 |

### CODE REVIEW

**Comment by sphism** [comment]
@HyperSimon that's a great solution

**Comment by cmprescott** [comment]
@HyperSimon thanks for this!

**Comment by gusbueno** [comment]
Thanks dude! great solution!

**Comment by AdriaRios** [comment]
What about the state of this PR?

**Comment by Infinity0106** [comment]
already added inside index.js

**Pull request closed without merging**
